Repository FRONTENDBOOTCAMP-11th/5MyGod, pull requests merged in 2024-12, with the labels that each got.

#6 메인페이지 기본 구조 작성 / 테일윈드 css 설정
  index.css
  package-lock.json
  package.json
  postcss.config.js
  src/pages/board/main_list.html
  tailwind.config.js
Labels: others

#11 💄 로그인 페이지 마크업
  src/pages/user/Login.html
Labels: feature

#13 메인페이지 마크업 완성 / svg 이미지 추가
  src/assets/adult.svg
  src/assets/calendar.svg
  src/assets/filter.svg
  src/assets/money.svg
  src/assets/pill.svg
  src/assets/search.svg
  src/assets/siren.svg
  src/assets/watch.svg
  src/assets/🌟 star.svg
  src/assets/👍🏻 thumb.svg
  src/assets/💕 twohearts.svg
  src/assets/🚹️ male.svg
  src/assets/🚺️ female.svg
  src/assets/🛵 bike.svg
  src/assets/🧞 genie.svg
  src/pages/board/main_list.html
Labels: feature

#17 💄✨ 회원가입 페이지 마크업
  src/pages/user/Login.html
  src/pages/user/Signup.html
Labels: enhancement, feature

#18 [feature] 글 작성 페이지 마크업 완성 / [assets] svg 이미지 추가
  src/assets/checked.svg
  src/assets/unchecked.svg
  src/pages/board/write.html
Labels: feature

#25 [feature] SPA 구조 및 라우팅 정의, 각종 환경설정 및 수정사항
  index.html
  jsconfig.json
  package-lock.json
  package.json
  public/assets/adult.svg
  public/assets/bike.svg
  public/assets/calendar.svg
  public/assets/check.svg
  public/assets/checked.svg
  public/assets/female.svg
  public/assets/filter.svg
  public/assets/genie.svg
  public/assets/landline.svg
  public/assets/male.svg
  public/assets/money.svg
  public/assets/pill.svg
  public/assets/pin.svg
  public/assets/react.svg
  public/assets/redwatch.svg
  public/assets/search.svg
  public/assets/siren.svg
  public/assets/star.svg
  public/assets/thumb.svg
  public/assets/twohearts.svg
  public/assets/unchecked.svg
  public/assets/watch.svg
  src/App.jsx
  src/assets/bike.svg
  src/assets/female.svg
  src/assets/genie.svg
  src/assets/male.svg
  src/assets/star.svg
  src/assets/thumb.svg
  src/assets/twohearts.svg
  src/components/layout/Footer.jsx
  src/components/layout/Header.jsx
  src/components/layout/index.jsx
  src/main.jsx
  src/pages/MainPage.jsx
  src/pages/main_list.html
  src/routes.jsx
  src/styles/index.css
  vite.config.js
Labels: enhancement, feature, fix, others

#29 🗃️ db: DB 초기화 - 회원, 게시물, 카테고리, 태그 더미데이터를 DB에 등록
  api/bruno-onyourway/01 회원/03. 회원 목록 조회/회원 목록 조회.bru
  api/bruno-onyourway/02 상품(심부름 요청)/01. 목록 조회/상품(심부름 요청) 목록 조회.bru
  api/bruno-onyourway/bruno.json
  api/bruno-onyourway/collection.bru
  api/bruno-onyourway/environments/bruno-onyourway.bru
  api/dbinit-onyourway/.env
  api/dbinit-onyourway/getDB.js
  api/dbinit-onyourway/init.js
  api/dbinit-onyourway/openmarket/data.js
  api/dbinit-onyourway/openmarket/uploadFiles/user-apeach.webp
  api/dbinit-onyourway/openmarket/uploadFiles/user-jayg.webp
  api/dbinit-onyourway/openmarket/uploadFiles/user-muzi.webp
  api/dbinit-onyourway/openmarket/uploadFiles/user-neo.webp
  api/dbinit-onyourway/package-lock.json
  api/dbinit-onyourway/package.json
Labels: others

#31 ✨ feature: useAxiosInstance 훅 추가
  src/hooks/useAxiosInstance.js
Labels: feature

#32 [feature] TagList, ListItem, MainPage(List) 동적 컴포넌트 구현 완료
  .github/PULL_REQUEST_TEMPLATE.md
  api/dbinit-onyourway/openmarket/data.js
  package-lock.json
  package.json
  src/pages/MainPage.jsx
  src/pages/board/Detail.jsx
  src/pages/board/ListItem.jsx
  src/pages/board/MainPage.jsx
  src/pages/board/TagList.jsx
  src/pages/board/main_list.html
  src/routes.jsx
Labels: feature

#34 🗃️ db: 게시물 더미데이터 추가
  .github/PULL_REQUEST_TEMPLATE.md
  api/dbinit-onyourway/openmarket/data.js
Labels: others
