Repository FRONTENDBOOTCAMP-11th/5MyGod, pull requests merged in 2025-01, with the labels that each got.

#38 🗃️ DB: 유저 더미데이터에 성별, 좋아요 수 추가
  api/dbinit-onyourway/openmarket/data.js
Labels: others

#40 [feature] 회원가입 페이지 JSX로 변환 및 API 연결
  src/pages/user/Signup.jsx
  src/routes.jsx
  src/zustand/userGenderStore.js
Labels: enhancement, feature

#44 [feature] 상세보기 페이지 구현 완료
  api/dbinit-onyourway/openmarket/data.js
  index.html
  public/assets/adult.png
  public/assets/bike.png
  public/assets/calendar.png
  public/assets/checked.png
  public/assets/female.png
  public/assets/filter.png
  public/assets/genie.png
  public/assets/landline.png
  public/assets/male.png
  public/assets/money.png
  public/assets/moneypouch.png
  public/assets/pin.png
  public/assets/redwatch.png
  public/assets/search.png
  public/assets/siren.png
  public/assets/star.png
  public/assets/thumb.png
  public/assets/twohearts.png
  public/assets/unchecked.png
  public/assets/watch.png
  src/assets/adult.png
  src/assets/bike.png
  src/assets/calendar.png
  src/assets/check.svg
  src/assets/checked.png
  src/assets/female.png
  src/assets/filter.png
  src/assets/genie.png
  src/assets/landline.png
  src/assets/male.png
  src/assets/money.png
  src/assets/moneypouch.png
  src/assets/pill.svg
  src/assets/pin.png
  src/assets/redwatch.png
  src/assets/search.png
  src/assets/siren.png
  src/assets/star.png
  src/assets/thumb.png
  src/assets/twohearts.png
  src/assets/unchecked.png
  src/assets/watch.png
  src/components/LocationMap.jsx
  src/pages/board/Detail.jsx
  src/routes.jsx
Labels: feature, others

#48 🐛 fix: 라우팅 오류 해결
  src/routes.jsx
Labels: fix

#50 [feature] 댓글목록, 댓글아이템, 댓글작성 컴포넌트 개발 완료
  api/bruno-onyourway/01 회원/01.회원가입,로그인/로그인.bru
  api/bruno-onyourway/02 상품(심부름 요청)/02. 댓글/01. 댓글 달기.bru
  api/bruno-onyourway/environments/bruno-onyourway.bru
  api/dbinit-onyourway/openmarket/data.js
  eslint.config.js
  package-lock.json
  package.json
  src/components/InputError.jsx
  src/pages/board/CommentList.jsx
  src/pages/board/CommentListItem.jsx
  src/pages/board/CommentNew.jsx
  src/pages/board/Detail.jsx
  src/pages/board/ListItem.jsx
  src/zustand/userStore.js
Labels: enhancement, feature, others

#53 [others] 브루노 토큰 설정 변경
  api/bruno-onyourway/collection.bru
  api/bruno-onyourway/environments/bruno-onyourway.bru
Labels: others

#49 ✨ 마이페이지 마크업
  public/assets/heart.png
  src/assets/heart.png
  src/pages/user/Mypage.jsx
  src/pages/user/Profile.jsx
  src/pages/user/Tabs.jsx
  src/routes.jsx
Labels: enhancement, feature

#57 [feature] 지원자 프로필 페이지 마크업
  src/pages/user/Mypage.jsx
  src/pages/user/Profile.jsx
  src/pages/user/UserPage.jsx
  src/routes.jsx
Labels: feature

#61 🗃️ DB: 주문(지원) 상태 코드 수정, 주문(지원) 아이템 하나 완성해서 등록
  api/dbinit-onyourway/openmarket/data.js
Labels: others

#63 [others] DB 업데이트
  api/dbinit-onyourway/openmarket/data.js
Labels: others

#67 [feature] 마이페이지 1차
  src/hooks/useAxiosInstance.js
  src/pages/user/ApplyList.jsx
  src/pages/user/Login.html
  src/pages/user/Login.jsx
  src/pages/user/Mypage.html
  src/pages/user/Mypage.jsx
  src/pages/user/RequestList.jsx
  src/pages/user/Signup.html
Labels: enhancement, feature

#74 [feature51] 심부름 작성 페이지 완성
  api/bruno-onyourway/01 회원/01.회원가입,로그인/로그인.bru
  api/bruno-onyourway/02 상품(심부름 요청)/03. 상품 등록(심부름 요청).bru
  api/bruno-onyourway/03 내 지원관리/내 지원목록.bru
  api/bruno-onyourway/03 내 지원관리/부탁한 심부름.bru
  index.html
  package-lock.json
  package.json
  src/components/DateandTimePicker.jsx
  src/components/layout/index.jsx
  src/pages/board/Detail.jsx
  src/pages/board/ListItem.jsx
  src/pages/board/MainPage.jsx
  src/pages/board/New.jsx
  src/pages/board/TagList.jsx
  src/routes.jsx
  src/styles/index.css
  tailwind.config.js
Labels: enhancement, feature, fix, others

#77 [Enhance76] 리스트아이템 동작과 구분 추가
  src/pages/board/ListItem.jsx
  src/pages/board/TagList.jsx
  src/routes.jsx
Labels: enhancement

#72 [others] DB 유저 속성 추가
  5MyGod/bruno.json
  api/bruno-onyourway/03 마이페이지/내 요청 목록 조회.bru
  api/bruno-onyourway/03 마이페이지/내 지원 목록 조회.bru
  api/bruno-onyourway/5MyGod/bruno.json
  src/pages/user/ApplyList.jsx
Labels: others

#91 DB 업데이트
  api/dbinit-onyourway/openmarket/data.js
Labels: others

#92 [FEATURE] 마이페이지 현재 작업 푸쉬, db 유저 데이터 추가
  api/dbinit-onyourway/openmarket/data.js
  api/dbinit-onyourway/package-lock.json
  src/pages/board/ListItem.jsx
  src/pages/user/MyApplies.jsx
  src/pages/user/MyRequests.jsx
  src/pages/user/Mypage.jsx
  src/pages/user/Profile.jsx
  src/pages/user/UserPage.jsx
  src/routes.jsx
Labels: feature, others

#96 심부름 관련 모든 버튼과 기능 추가, 리스트아이템 업데이트
  5MyGod/bruno.json
  api/bruno-onyourway/01 회원/로그인.bru
  api/bruno-onyourway/01 회원/회원 목록 조회.bru
  api/bruno-onyourway/02 상품(심부름 요청)/01. 목록 조회/상품(심부름 요청) 목록 조회.bru
  api/bruno-onyourway/02 상품(심부름)/댓글 달기.bru
  api/bruno-onyourway/02 상품(심부름)/심부름 목록 조회.bru
  api/bruno-onyourway/02 상품(심부름)/심부름 요청 올리기.bru
  api/bruno-onyourway/02 상품(심부름)/지원하기.bru
  api/bruno-onyourway/03 내 지원관리/내 지원목록.bru
  api/bruno-onyourway/04 마이페이지/내 요청 목록 조회.bru
  api/bruno-onyourway/04 마이페이지/내 지원 목록 조회.bru
  api/bruno-onyourway/5MyGod/bruno.json
  src/components/LocationMap.jsx
  src/components/layout/index.jsx
  src/pages/board/Applicants.jsx
  src/pages/board/Detail.jsx
  src/pages/board/ListItem.jsx
  src/pages/board/MainPage.jsx
  src/pages/board/New.jsx
  src/routes.jsx
Labels: enhancement, feature

#101 Enhance98/main page/juseok
  src/pages/board/MainPage.jsx
  src/pages/board/New.jsx
Labels: enhancement, feature

#103 DB 업데이트: 상품(심부름) 데이터에 누구랑 매칭되었는지 속성 추가
  api/dbinit-onyourway/openmarket/data.js
Labels: enhancement

#107 🗃️ DB: 상품 번호와 지원 번호를 모두 하드코딩으로 수정
  api/dbinit-onyourway/openmarket/data.js
Labels: fix

#109 상세보기 페이지의 '지원하기' 로직과 동작 수정, `data.js` 수정
  api/bruno-onyourway/03 주문(지원)/나에게 들어온 주문(지원) 목록 조회.bru
  api/bruno-onyourway/03 주문(지원)/특정 상품에 내가 주문한 내역 조회 - 5번 심부름으로 테스트.bru
  api/dbinit-onyourway/openmarket/data.js
  src/pages/board/Detail.jsx
  src/pages/board/MainPage.jsx
  src/pages/pay/Payment.jsx
Labels: enhancement, fix, others

#113 Enhance111/detail page/juseok
  src/pages/board/Applicants.jsx
  src/pages/board/Detail.jsx
Labels: enhancement, feature

#115 상세보기 페이지에서 결제 컴포넌트 조건부 호출 및 props 전달
  src/pages/board/Detail.jsx
Labels: enhancement, feature

#117 🔧 네틀리파이 폴백 유아이 설정
  netlify.toml
Labels: others

#121 [Feature] 마이페이지 수정버튼 동작
  src/hooks/useAxiosInstance.js
  src/pages/user/Login.jsx
  src/pages/user/MyEdit.jsx
  src/pages/user/Mypage.jsx
  src/pages/user/edit/Introduction.jsx
Labels: enhancement, feature

#124 [fix] 상세보기페이지, 작성페이지 수정보완
  src/pages/board/Detail.jsx
  src/pages/board/New.jsx
Labels: enhancement, fix

#126 메인페이지 목록 필터링 제거, 리스트아이템 동적 스타일링 로직 추가
  api/bruno-onyourway/02 상품(심부름)/심부름 요청 올리기.bru
  api/bruno-onyourway/02 상품(심부름)/지원하기.bru
  api/bruno-onyourway/collection.bru
  src/pages/board/ListItem.jsx
  src/pages/board/MainPage.jsx
Labels: enhancement

#129 [feature] 마이페이지 css 수정, useAxiosInstance 401에러 수정
  src/hooks/useAxiosInstance.js
  src/pages/user/MyEdit.jsx
  src/pages/user/Mypage.jsx
  src/pages/user/UserPage.jsx
Labels: enhancement, fix

#134 [feature] 뒤로가기 버튼 클릭 시 탭 상태 유지
  src/pages/user/Mypage.jsx
Labels: enhancement, feature

#136 로그아웃 기능 구현
  src/pages/user/Logout.jsx
  src/pages/user/Mypage.jsx
Labels: feature

#138 상세보기 페이지, 결제버튼 개선보완 및 data.js 수정
  api/dbinit-onyourway/openmarket/data.js
  src/components/pay/Payment.jsx
  src/pages/board/Detail.jsx
Labels: enhancement, fix

#131 enhancement X 버튼추가
  src/components/layout/NavigationHeader.jsx
  src/components/pay/PaySuccess.jsx
Labels: enhancement

#152 🚑 주문 안의 상품번호가 엉뚱하게 들어가는 문제 해결
  api/dbinit-onyourway/openmarket/data.js
Labels: fix

#161 [fix] 뜨지 않는 이미지 경로 수정 및 이미지 추가
  public/assets/success.png
  src/components/pay/PaySuccess.jsx
Labels: fix

#169 [fix] 로그인 로그아웃 에러
  src/hooks/useAxiosInstance.js
  src/pages/board/New.jsx
  src/pages/user/Logout.jsx
  src/protected.jsx
  src/routes.jsx
Labels: fix

#163 [fix] mypage에 맞게 결제 완료 후 경로 수정
  src/components/pay/PaySuccess.jsx
Labels: fix

#172 배포 전 마지막 수정작업
  src/components/pay/Payment.jsx
  src/pages/user/Signup.jsx
  src/routes.jsx
Labels: fix

#175 🚑 마이페이지 오류 해결
  src/pages/user/Mypage.jsx
  src/pages/user/Profile.jsx
Labels: fix

#179 채팅 없는 기본 페이지 추가
  src/components/layout/NavigationHeader.jsx
  src/pages/chating/ChatsList.jsx
  src/routes.jsx
Labels: feature, fix

#180 DB 업데이트
  api/dbinit-onyourway/openmarket/data.js
  api/dbinit-onyourway/openmarket/uploadFiles/guy.webp
  api/dbinit-onyourway/openmarket/uploadFiles/jiwoo.webp
  api/dbinit-onyourway/openmarket/uploadFiles/kungya.webp
  api/dbinit-onyourway/openmarket/uploadFiles/sparrow.webp
  api/dbinit-onyourway/openmarket/uploadFiles/user-apeach.webp
  api/dbinit-onyourway/openmarket/uploadFiles/user-jayg.webp
  api/dbinit-onyourway/openmarket/uploadFiles/user-muzi.webp
  api/dbinit-onyourway/openmarket/uploadFiles/user-neo.webp
Labels: others

#184 지원 상태 관련 작업
  src/pages/board/Applicants.jsx
  src/pages/board/Detail.jsx
  src/pages/board/New.jsx
Labels: enhancement, fix

#188 [Fix] 마이페이지 수정 오류
  src/hooks/useAxiosInstance.js
  src/pages/user/Mypage.jsx
Labels: fix

#190 리스트아이템 문제 해결....
  api/bruno-onyourway/01 회원/로그인.bru
  api/bruno-onyourway/05 진행 중 심부름/진행 중인 요청 목록만 가져오기.bru
  api/bruno-onyourway/05 진행 중 심부름/진행 중인 지원 목록만 받아오기.bru
  src/pages/board/ListItem.jsx
  src/pages/board/MainPage.jsx
  src/pages/user/MyApplies.jsx
  src/pages/user/MyRequests.jsx
  src/pages/user/Mypage.jsx
  src/pages/user/OngoingErrands.jsx
Labels: enhancement, fix
